"""Generate the Kaggle-ready notebook.

The notebook is self-contained: the micro/ module sources are read from disk
AT BUILD TIME and inlined as cells, so the notebook can never drift from the
repo code. Re-run this script after changing micro/env.py, micro/cvml.py or
micro/policy.py, then push with ./kaggle_sync.sh push.
"""
import os
import nbformat as nbf

ROOT = os.path.dirname(os.path.abspath(__file__))

# ── Smoke-test config baked into the generated notebook ──────────────────────
TRAIN_TIMESTEPS = 10_000     # set to 500_000 for a full run

nb = nbf.v4.new_notebook()
# Kaggle's papermill runner requires an explicit kernelspec
nb.metadata["kernelspec"] = {
    "name": "python3",
    "display_name": "Python 3",
    "language": "python",
}
nb.metadata["language_info"] = {"name": "python"}


def md(source):
    nb.cells.append(nbf.v4.new_markdown_cell(source))


def code(source):
    nb.cells.append(nbf.v4.new_code_cell(source))


def module_source(relpath):
    """Read a repo module and adapt it for inline notebook use:
    strip package-relative imports (classes come from earlier cells)
    and the __main__ demo block."""
    with open(os.path.join(ROOT, relpath), encoding="utf-8") as f:
        src = f.read()

    lines = []
    for ln in src.splitlines():
        stripped = ln.strip()
        if stripped.startswith("from .") or stripped.startswith("from micro.") \
                or stripped.startswith("from macro."):
            continue
        lines.append(ln)
    src = "\n".join(lines)

    idx = src.find('if __name__ == "__main__":')
    if idx != -1:
        src = src[:idx].rstrip() + "\n"
    return f"# ── Inlined from {relpath} (auto-generated by build_notebook.py) ──\n{src}"


# ═════════════════════════════════════════════════════════════════════════════
# CELL: Title
# ═════════════════════════════════════════════════════════════════════════════
md(f"""# 🤖 Hierarchical Dual-Frequency DRL Trading Bot

**Architecture**: Macro LLM Swarm (news → 5 LLM personas → consensus scalars + embedding,
**time-aligned** to LOB rows) + Micro CVML (10-level LOB → Conv2D → 64D) → PPO.

**Protocol**: models train on the first 70% of the data (random episode starts) and are
evaluated **out-of-sample** on the held-out last 30%, against Buy&Hold / TWAP / VWAP / Random
baselines and two ablations (macro zeroed, flat MLP).

Smoke-test config: **{TRAIN_TIMESTEPS:,} timesteps** per model.
This notebook is generated by `build_notebook.py` — module code is inlined from the repo
sources automatically. Do not edit the inlined cells by hand.

---""")

# ═════════════════════════════════════════════════════════════════════════════
# CELL: Install + imports + GPU check
# ═════════════════════════════════════════════════════════════════════════════
code("""# ── Install Dependencies ─────────────────────────────────────────────────────
!pip install -q stable-baselines3 gymnasium

import os, sys, time, csv
import numpy as np
import pandas as pd
import torch
import gymnasium as gym
from gymnasium import spaces
import torch.nn as nn
from stable_baselines3 import PPO
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.callbacks import BaseCallback, CheckpointCallback

print(f"torch {torch.__version__} | CUDA available: {torch.cuda.is_available()}")
for i in range(torch.cuda.device_count()):
    print(f"  GPU {i}: {torch.cuda.get_device_name(i)}")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu\"""")

# ═════════════════════════════════════════════════════════════════════════════
# CELL: Config
# ═════════════════════════════════════════════════════════════════════════════
code(f"""# ── CONFIGURATION ────────────────────────────────────────────────────────────
import glob

ON_KAGGLE = os.path.exists("/kaggle/input")
OUT_DIR = "/kaggle/working" if ON_KAGGLE else "notebooks/out"
MODELS_DIR = os.path.join(OUT_DIR, "models")
os.makedirs(MODELS_DIR, exist_ok=True)

if ON_KAGGLE:
    # Discover the mounted dataset rather than guessing its slug
    hits = glob.glob("/kaggle/input/**/lobster_aapl_10_level.csv", recursive=True)
    if not hits:
        print("Contents of /kaggle/input:")
        for root, dirs, files in os.walk("/kaggle/input"):
            for name in files:
                print(" ", os.path.join(root, name))
        raise FileNotFoundError(
            "lobster_aapl_10_level.csv not found under /kaggle/input — "
            "is the drl-trading-lob-data dataset attached and processed?")
    DATA_DIR = os.path.dirname(hits[0])
else:
    DATA_DIR = "data/raw"

DATA_PATH = os.path.join(DATA_DIR, "lobster_aapl_10_level.csv")
MACRO_PATH = os.path.join(DATA_DIR, "macro_vectors.npz")
if not os.path.exists(MACRO_PATH):
    MACRO_PATH = None

TRAIN_TIMESTEPS = {TRAIN_TIMESTEPS}   # smoke test; set 500_000 for a full run
REWARD_TYPE = "log_return"            # "log_return" | "sharpe" | "pnl"
TRAIN_FRAC = 0.7                      # first 70% of rows = training window
TRAIN_EPISODE_STEPS = 256             # episode length during training

RUN_LOG = os.path.join(OUT_DIR, "run_log.txt")
def log_line(msg):
    print(msg)
    with open(RUN_LOG, "a") as f:
        f.write(msg + "\\n")

log_line(f"data={{DATA_PATH}}")
log_line(f"macro={{MACRO_PATH}}")
log_line(f"timesteps={{TRAIN_TIMESTEPS:,}} reward={{REWARD_TYPE}} device={{DEVICE}}")""")

# ═════════════════════════════════════════════════════════════════════════════
# CELLS: Inlined module sources (single source of truth = repo files)
# ═════════════════════════════════════════════════════════════════════════════
md("""## 1. CVML — Convolutional Cross-Variate Mixing Layer
Depthwise conv over adjacent price levels + pointwise conv mixing the 4 variates.
Input layout must match `canonical_lob_columns()`: `[bid_p1..10, ask_p1..10, bid_s1..10, ask_s1..10]`.""")
code(module_source("micro/cvml.py"))

md("""## 2. LOBReplayEnv — Gymnasium Environment
Windowed replay (train/test split), random episode starts, market frictions,
and **time-aligned macro vectors**: each row sees the most recent news event at
or before its own timestamp (4 consensus scalars + 128 pooled embedding dims).""")
code(module_source("micro/env.py"))

md("""## 3. Feature Extractors — SB3 Custom Policies""")
code(module_source("micro/policy.py"))

# ═════════════════════════════════════════════════════════════════════════════
# CELL: Training harness
# ═════════════════════════════════════════════════════════════════════════════
md("""## 4. Training — PPO variants
- **PPO+CVML+Macro** — full model
- **PPO+CVML (no macro)** — macro vector zeroed (macro ablation)
- **PPO+FlatMLP** — flat MLP instead of CVML (architecture ablation)""")
code("""HYPERPARAMS = {
    "learning_rate": 3e-4,
    "n_steps": 2048,
    "batch_size": 64,
    "n_epochs": 10,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "ent_coef": 0.01,
    "vf_coef": 0.5,
    "max_grad_norm": 0.5,
    "clip_range": 0.2,
}


def make_env(train=True, zero_macro=False, max_steps=None):
    if train:
        return LOBReplayEnv(
            data_path=DATA_PATH, use_macro_vector=True, macro_vectors_path=MACRO_PATH,
            zero_macro=zero_macro, reward_type=REWARD_TYPE, inventory_penalty=0.001,
            max_inventory=50, invalid_action_penalty=0.01,
            start_frac=0.0, end_frac=TRAIN_FRAC, random_start=True,
            max_steps=TRAIN_EPISODE_STEPS)
    return LOBReplayEnv(
        data_path=DATA_PATH, use_macro_vector=True, macro_vectors_path=MACRO_PATH,
        zero_macro=zero_macro, reward_type=REWARD_TYPE, inventory_penalty=0.001,
        max_inventory=50, invalid_action_penalty=0.01,
        start_frac=TRAIN_FRAC, end_frac=1.0, random_start=False, max_steps=max_steps)


def linear_schedule(initial_lr):
    def schedule(progress_remaining):
        return progress_remaining * initial_lr
    return schedule


class MetricsLoggerCallback(BaseCallback):
    def __init__(self, log_path, verbose=0):
        super().__init__(verbose)
        self.log_path = log_path
        self.episode_rewards, self.episode_lengths = [], []
        with open(self.log_path, "w", newline="") as f:
            csv.writer(f).writerow([
                "timestep", "episodes", "mean_reward", "mean_length",
                "entropy_loss", "policy_loss", "value_loss", "learning_rate"])

    def _on_step(self):
        for info in self.locals.get("infos", []):
            if "episode" in info:
                self.episode_rewards.append(info["episode"]["r"])
                self.episode_lengths.append(info["episode"]["l"])
        return True

    def _on_rollout_end(self):
        if not self.episode_rewards:
            return
        logger = self.model.logger
        with open(self.log_path, "a", newline="") as f:
            csv.writer(f).writerow([
                self.num_timesteps, len(self.episode_rewards),
                np.mean(self.episode_rewards[-10:]), np.mean(self.episode_lengths[-10:]),
                logger.name_to_value.get("train/entropy_loss", 0),
                logger.name_to_value.get("train/policy_gradient_loss", 0),
                logger.name_to_value.get("train/value_loss", 0),
                self.model.lr_schedule(self.model._current_progress_remaining)])


def train_model(model_name, use_cvml=True, zero_macro=False,
                total_timesteps=TRAIN_TIMESTEPS):
    log_line(f"\\n=== TRAIN {model_name} | {total_timesteps:,} steps ===")
    env = make_env(train=True, zero_macro=zero_macro)
    extractor = HierarchicalFeatureExtractor if use_cvml else FlatMLPFeatureExtractor
    model = PPO(
        "MultiInputPolicy", env,
        policy_kwargs={"features_extractor_class": extractor,
                       "features_extractor_kwargs": {},
                       "net_arch": [256, 128, 64]},
        verbose=1,
        learning_rate=linear_schedule(HYPERPARAMS["learning_rate"]),
        n_steps=HYPERPARAMS["n_steps"], batch_size=HYPERPARAMS["batch_size"],
        n_epochs=HYPERPARAMS["n_epochs"], gamma=HYPERPARAMS["gamma"],
        gae_lambda=HYPERPARAMS["gae_lambda"], ent_coef=HYPERPARAMS["ent_coef"],
        vf_coef=HYPERPARAMS["vf_coef"], max_grad_norm=HYPERPARAMS["max_grad_norm"],
        clip_range=HYPERPARAMS["clip_range"], device=DEVICE)

    t0 = time.time()
    model.learn(total_timesteps=total_timesteps,
                callback=[MetricsLoggerCallback(os.path.join(OUT_DIR, f"training_log_{model_name}.csv"))])
    model.save(os.path.join(MODELS_DIR, f"{model_name}_final"))
    log_line(f"{model_name}: trained in {time.time()-t0:.1f}s, saved to {MODELS_DIR}")
    return model""")

md("""### 4a. Train all three variants""")
code("""cvml_model = train_model("ppo_cvml", use_cvml=True)""")
code("""nomacro_model = train_model("ppo_cvml_nomacro", use_cvml=True, zero_macro=True)""")
code("""flat_model = train_model("ppo_flat", use_cvml=False)""")

# ═════════════════════════════════════════════════════════════════════════════
# CELL: Baselines + evaluation
# ═════════════════════════════════════════════════════════════════════════════
md("""## 5. Out-of-Sample Evaluation — held-out last 30% of the data""")
code("""def evaluate_agent(model, env, name="Agent"):
    obs, _ = env.reset()
    done, total_reward = False, 0.0
    while not done:
        action, _ = model.predict(obs, deterministic=True)
        obs, reward, done, truncated, info = env.step(action)
        total_reward += reward
        if truncated:
            break
    stats = env.get_episode_stats()
    stats["total_reward"] = round(total_reward, 4)
    stats["name"] = name
    return stats


def run_buy_hold(env):
    obs, _ = env.reset()
    done = False
    while not done:
        row = env.df.iloc[env.current_step]
        action = 1 if env.cash >= float(row["ask_price_1"]) * 1.001 and env.inventory < env.max_inventory else 0
        obs, r, done, trunc, info = env.step(action)
        if trunc:
            break
    stats = env.get_episode_stats(); stats["name"] = "Buy&Hold"
    return stats


def run_twap(env):
    obs, _ = env.reset()
    done, steps = False, 0
    horizon = env._window_hi - env.current_step
    while not done:
        if steps % 50 == 0 and steps < horizon - 100 and env.inventory < env.max_inventory:
            action = 1
        elif steps >= horizon - 50 and env.inventory > 0:
            action = 2
        else:
            action = 0
        obs, r, done, trunc, info = env.step(action)
        steps += 1
        if trunc:
            break
    stats = env.get_episode_stats(); stats["name"] = "TWAP"
    return stats


def run_vwap(env):
    obs, _ = env.reset()
    done, steps, total_volume_seen = False, 0, 0
    horizon = env._window_hi - env.current_step
    while not done:
        row = env.df.iloc[env.current_step]
        bid_vol = sum(float(row.get(f"bid_size_{i}", 0)) for i in range(1, 6))
        ask_vol = sum(float(row.get(f"ask_size_{i}", 0)) for i in range(1, 6))
        total_vol = bid_vol + ask_vol
        total_volume_seen += total_vol
        avg_vol = total_volume_seen / max(steps + 1, 1)
        if total_vol > avg_vol * 1.2 and steps < horizon - 100 and env.inventory < env.max_inventory:
            action = 1
        elif steps >= horizon - 50 and env.inventory > 0:
            action = 2
        elif total_vol < avg_vol * 0.8 and env.inventory > 0:
            action = 2
        else:
            action = 0
        obs, r, done, trunc, info = env.step(action)
        steps += 1
        if trunc:
            break
    stats = env.get_episode_stats(); stats["name"] = "VWAP"
    return stats


def run_random(env, seed=42):
    obs, _ = env.reset()
    done, rng = False, np.random.RandomState(seed)
    while not done:
        obs, r, done, trunc, info = env.step(rng.randint(0, 5))
        if trunc:
            break
    stats = env.get_episode_stats(); stats["name"] = "Random"
    return stats""")

code("""all_stats = []
all_stats.append(evaluate_agent(cvml_model, make_env(train=False), "PPO+CVML+Macro"))
all_stats.append(evaluate_agent(nomacro_model, make_env(train=False, zero_macro=True), "PPO+CVML"))
all_stats.append(evaluate_agent(flat_model, make_env(train=False), "PPO+FlatMLP"))
for runner in (run_buy_hold, run_twap, run_vwap, run_random):
    all_stats.append(runner(make_env(train=False)))

headers = ["Model", "Return%", "Sharpe", "MaxDD%", "Trades", "Buy", "Sell", "Final PV", "Inv"]
widths = [18, 10, 10, 10, 8, 6, 6, 12, 8]
log_line("\\n" + "=" * 98)
log_line("OUT-OF-SAMPLE EVALUATION (held-out last 30% of data)".center(98))
log_line("=" * 98)
log_line("".join(f"{h:>{w}}" for h, w in zip(headers, widths)))
log_line("-" * 98)
for s in all_stats:
    log_line(f"{s['name']:>18}{s['total_return_pct']:>10.4f}{s['sharpe_ratio']:>10.4f}"
             f"{s['max_drawdown_pct']:>10.4f}{s['total_trades']:>8}{s['buy_trades']:>6}"
             f"{s['sell_trades']:>6}  ${s['final_pv']:>9.2f}{s['final_inventory']:>8}")
log_line("=" * 98)""")

# ═════════════════════════════════════════════════════════════════════════════
# CELL: Equity curves
# ═════════════════════════════════════════════════════════════════════════════
md("""## 6. Equity Curves (test window)""")
code("""import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(12, 5))
for model, label in ((cvml_model, "PPO+CVML+Macro"),
                     (nomacro_model, "PPO+CVML (no macro)"),
                     (flat_model, "PPO+FlatMLP")):
    env = make_env(train=False, zero_macro=(label == "PPO+CVML (no macro)"))
    evaluate_agent(model, env, label)
    ax.plot(env.portfolio_history, label=label, linewidth=1.2)

env = make_env(train=False)
run_buy_hold(env)
ax.plot(env.portfolio_history, label="Buy&Hold", linestyle="--", linewidth=1.2)

ax.set_xlabel("Test-window step"); ax.set_ylabel("Portfolio value ($)")
ax.set_title("Out-of-sample equity curves")
ax.legend(); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "equity_curves.png"), dpi=120)
plt.show()
log_line(f"\\nSaved equity_curves.png; artifacts in {OUT_DIR}")""")

md(f"""## 🚀 Scale up
This was a **{TRAIN_TIMESTEPS:,}-step smoke test**. For a real run, edit
`TRAIN_TIMESTEPS = 500_000` in `build_notebook.py`, regenerate, and push again.
Macro vectors: `python macro/run_swarm_batch.py --max-events 500` locally, then
`./kaggle_sync.sh data-update` so the dataset carries the refreshed `macro_vectors.npz`.""")

# ═════════════════════════════════════════════════════════════════════════════
# Write notebook
# ═════════════════════════════════════════════════════════════════════════════
out_path = os.path.join(ROOT, "notebooks", "drl_trading_pipeline.ipynb")
with open(out_path, "w", encoding="utf-8") as f:
    nbf.write(nb, f)
print(f"Notebook written to {out_path} ({len(nb.cells)} cells, "
      f"TRAIN_TIMESTEPS={TRAIN_TIMESTEPS:,})")
